version: "3"

services:
  app:
    image: ghcr.io/locrealloc/abisurvey:latest
    # image: ghcr.io/locrealloc/abisurvey:develop
    container_name: abisurvey
    restart: always
    depends_on:
      - database
    env_file:
      - .env.local
    ports:
      - "3000:3000"
  database:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
